runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: yarn config set nodeLinker pnp
      shell: bash

    - run: yarn install --no-immutable
      shell: bash
