runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - run: corepack enable
      shell: bash

    - run: yarn set version berry
      shell: bash

    - run: yarn config set nodeLinker node-modules
      shell: bash

    - run: yarn install --no-immutable
      shell: bash
